/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package axon-form/core */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 5 "ffi_wrapper.go"

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

typedef void (*dart_json_callback)(char* json_data);

static void invoke_callback(void* callback_ptr, char* json_data) {
    if (callback_ptr == NULL) return;
    dart_json_callback cb = (dart_json_callback)callback_ptr;
    cb(json_data);
}

static void debug_print(char* str) {
    printf("[Native] %s\n", str);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* ResultPtr();
extern int ResultLen();
extern char* GetResult();
extern int InitGraph(void* dataPtr, int dataLen);
extern int AddEventListener(void* eventPtr, int eventLen, void* callbackPtr);
extern int IsNodeVisible(void* nodeIDPtr, int nodeIDLen);
extern int GetChildNode(void* nodeIDPtr, int nodeIDLen);
extern int GetOptionNodes(void* nodeIDPtr, int nodeIDLen);
extern int ValidateAddressNode(void* nodeIDPtr, int nodeIDLen, void* valuePtr, int valueLen);
extern int ValidateNode(void* nodeIDPtr, int nodeIDLen, void* valuePtr, int valueLen);
extern int GetFormValue();
extern int GetPageFormValue(void* pageIDPtr, int pageIDLen);
extern void enforce_binding();

#ifdef __cplusplus
}
#endif
